# Generated by Django 4.2.7 on 2025-05-19 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developer_name",
                    models.CharField(
                        max_length=255, verbose_name="Название застройщика"
                    ),
                ),
                (
                    "developer_type",
                    models.CharField(max_length=100, verbose_name="Тип застройщика"),
                ),
            ],
            options={
                "verbose_name": "Застройщик",
                "verbose_name_plural": "Застройщики",
                "db_table": "developers",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(max_length=255, verbose_name="Название района"),
                ),
                (
                    "district_type",
                    models.CharField(max_length=50, verbose_name="Тип района"),
                ),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="FinancialInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=255, verbose_name="Название учреждения"
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(max_length=100, verbose_name="Тип учреждения"),
                ),
            ],
            options={
                "verbose_name": "Финансовое учреждение",
                "verbose_name_plural": "Финансовые учреждения",
                "db_table": "financial_institutions",
            },
        ),
        migrations.CreateModel(
            name="PredictionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "investment_strategy",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "inflation_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "central_bank_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "consumer_price_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gdp_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "mortgage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "deposit_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос прогноза",
                "verbose_name_plural": "Запросы прогнозов",
                "db_table": "prediction_requests",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complex_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("encumbrance_duration", models.IntegerField(blank=True, null=True)),
                (
                    "encumbrance_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("assignment", models.BooleanField(blank=True, null=True)),
                ("lots_bought", models.IntegerField(blank=True, null=True)),
                ("legal_entity_buyer", models.BooleanField(blank=True, null=True)),
                (
                    "property_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("mortgage", models.BooleanField(blank=True, null=True)),
                ("finishing", models.CharField(blank=True, max_length=100, null=True)),
                ("zone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "completion_stage",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("frozen", models.BooleanField(blank=True, null=True)),
                ("pd_issued", models.BooleanField(blank=True, null=True)),
                ("room_type", models.CharField(blank=True, max_length=50, null=True)),
                ("studio", models.BooleanField(blank=True, null=True)),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.financialinstitution",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
            options={
                "db_table": "properties_institutions",
                "unique_together": {("property", "institution")},
            },
        ),
        migrations.CreateModel(
            name="PropertyDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.district"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
            options={
                "db_table": "properties_districts",
                "unique_together": {("property", "district")},
            },
        ),
        migrations.CreateModel(
            name="PropertyDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.developer"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
            options={
                "db_table": "properties_developers",
                "unique_together": {("property", "developer")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="developers",
            field=models.ManyToManyField(
                through="core.PropertyDeveloper", to="core.developer"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="districts",
            field=models.ManyToManyField(
                through="core.PropertyDistrict", to="core.district"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="financial_institutions",
            field=models.ManyToManyField(
                through="core.PropertyInstitution", to="core.financialinstitution"
            ),
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_type", models.CharField(max_length=50)),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("influence_factors", models.JSONField()),
                ("price_dynamics", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "prediction_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.predictionrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат прогноза",
                "verbose_name_plural": "Конфигурации внешних БД",
                "db_table": "prediction_results",
                "ordering": ["prediction_request", "scenario_type"],
            },
        ),
        migrations.AddField(
            model_name="predictionrequest",
            name="property_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.property"
            ),
        ),
        migrations.AddField(
            model_name="predictionrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_type", models.CharField(max_length=50)),
                ("date_value", models.DateField(blank=True, null=True)),
                ("day_of_week", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("quarter", models.IntegerField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
            options={
                "db_table": "dates",
            },
        ),
    ]
