# Generated by Django 4.2.7 on 2025-05-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="property",
            name="completion_stage",
        ),
        migrations.RemoveField(
            model_name="property",
            name="encumbrance_duration",
        ),
        migrations.RemoveField(
            model_name="property",
            name="encumbrance_type",
        ),
        migrations.RemoveField(
            model_name="property",
            name="frozen",
        ),
        migrations.RemoveField(
            model_name="property",
            name="legal_entity_buyer",
        ),
        migrations.RemoveField(
            model_name="property",
            name="lots_bought",
        ),
        migrations.RemoveField(
            model_name="property",
            name="mortgage",
        ),
        migrations.RemoveField(
            model_name="property",
            name="pd_issued",
        ),
        migrations.RemoveField(
            model_name="property",
            name="price_per_sqm",
        ),
        migrations.RemoveField(
            model_name="property",
            name="room_type",
        ),
        migrations.RemoveField(
            model_name="property",
            name="studio",
        ),
        migrations.RemoveField(
            model_name="property",
            name="zone",
        ),
    ]
